### PR TITLE
Fix a bug where the arguments were ignored during logger setup

### LINKED ISSUE #93: Arguments are getting ignored during logger setup
The logger-related arguments are getting ignored during the logger setup, since the logger setup happens _before_ the command line arguments are parsed, see: https://github.com/webdevops/azure-devops-exporter/blob/881f0f7a80f26d714459e2bc518ff7fca2249372/main.go#L39-L40

This is a regression caused by my own pull request, see the changes [here](https://github.com/webdevops/azure-devops-exporter/pull/77/files#diff-2873f79a86c0d8b3335cd7731b0ecf7dd4301eb19a82ef7a1cba7589b5252261) (sorry about that).

However, the argument parser also depends on the logger, causing it to crash with a nil reference exception in case the arguments are invalid. Therefore, `initArgparser` should probably split up, so that the correct order of initialization would be:

1. Initialize the command line parser
2. Initialize the logger
3. Validate the options

I will create a pull request for this.

### PR DESCRIPTION
**Pull request by moredatapls**
Fixes #93

### CODE REVIEW

File: main.go [hunk 1]
```diff
@@ -70,7 +71,10 @@ func initArgparser() {
 			os.Exit(1)
 		}
 	}
+}
 
+// parses and validates the arguments
+func parseArguments() {
```
Comment (moredatapls) [inline main.go:77]: SonarCloud complains about the complexity of this method but I would prefer to not refactor this now

**Review by mblaschke — APPROVED** [review]
