### PR TITLE
Fix an issue where the resty clients weren't initialized correctly

### LINKED ISSUE #86: Getting 404 in the release definitions API
Lately, we are seeing a lot of 404 errors in the `release/definitions` API. If I attempt to directly access the API (e.g. via the browser), I also get a 404 error. I tried API versions 5.1 and 7.1 and the error persists in both versions.

Does anybody know why this error occurs? Are other people also facing this error?

A log of the one of the errors (happens for many of our projects, i.e. various project IDs):

```
2024-04-17T12:51:40.640Z    error    azure-devops-exporter/metrics_deployment.go:81    response status code is 404 (expected 200), url: https://dev.azure.com/...org.../...projectid.../_apis/release/definitions?api-version=7.1&isDeleted=false&$top=100&$expand=environments,lastRelease    {"collector": "Deployment", "project": "...projectName..."}
```

### PR DESCRIPTION
**Pull request by moredatapls**
The `restWithAuthentication` function always only used `c.restClient`, even if a `c.restClientVsrm` was requested.

Fix it by passing pointers to the respective function.

Fixes #86

I tested the changes locally against our DevOps instance and I didn't see the 404 errors anymore

### CODE REVIEW

**Comment by moredatapls** [comment]
Any chance that this can be reviewed and merged soon-ish @mblaschke? It would help us greatly :) Thank you for your efforts

**Review by mblaschke — APPROVED** [review]

File: azure-devops-client/main.go [hunk 1]
```diff
@@ -181,14 +179,13 @@ func (c *AzureDevopsClient) restVsrm() *resty.Client {
 	return client
 }
 
-func (c *AzureDevopsClient) restWithAuthentication(restClient **resty.Client, domain string) (*resty.Client, error) {
-
-	if *restClient == nil {
-		*restClient = c.restWithoutToken(domain)
+func (c *AzureDevopsClient) restWithAuthentication(restClient *resty.Client, domain string) (*resty.Client, error) {
+	if restClient == nil {
```
Comment (moredatapls) [inline azure-devops-client/main.go:183]: @mblaschke I see that you removed the double pointer I added here. I added this on purpose: assigning a value to `restClient` here will not update `c.restClient` that gets passed into this function. To make this work, I added the double pointer, so that I can actually update the `c.restClient` field.

Therefore, the client will not get cached in the devops client object (`c.restClient` will always be `nil`), `if restClient == nil` statement will always evaluate to `true`, and the client will always get reinitialized.
